# DSTT Assignment 2

## Q1

### a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape. Hint : arange

In [1]:
#Importing numpy
import numpy as np

var1 = np.arange(0,31)

print(f"The shape of the array is {var1.shape}")
print(var1)

The shape of the array is (31,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


### b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [9]:
var2 = var1.reshape(31,1)

print(f"The shape of var2 is {var2.shape}")
print(var2)

The shape of var2 is (31, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]


### c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape.

In [10]:
var3 = var1.reshape(1,31,1)

print(f"The shape of var3 is {var3.shape}")
print(var3)

The shape of var3 is (1, 31, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


### d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)

In [12]:
var2[1,0] = -1

print(var1)

[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [13]:
print(var3)

[[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


### Answer:-

As we can see that changing a value in var2, reflected the same in var1 and var3, at the respective position where the element would have been if reshaped to their shapes. The reason behind it is that the reshape function returns a view of the original numpy array, and thus any change in the view gets reflected in the original numpy array

### e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:

#### (i) Sum var3 over its second dimension and print the result.

#### (ii) Sum var3 over its third dimension and print the result.

#### (iii) Sum var3 over both its first and third dimensions and print the result.

In [15]:
# Solving (i)

result_sec_dim = np.sum(var3, axis=1)
print(f"The sum over second dimension is {result_sec_dim}")
print(f"The shape of the result is {result_sec_dim.shape}")

The sum over second dimension is [[463]]
The shape of the result is (1, 1)


In [16]:
# Solving (ii)
result_third_dim = np.sum(var3, axis=2)
print(f"The sum over third dimension is {result_third_dim}")
print(f"The shape of the result is {result_third_dim.shape}")

The sum over third dimension is [[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]
The shape of the result is (1, 31)


In [21]:
#Solving (iii)
result_first_third_dim = np.apply_over_axes(np.sum, var3, [0,2])
print(f"The sum over first and third dimensions is {result_first_third_dim}")
print(f"The shape of the result is {result_first_third_dim.shape}")

The sum over first and third dimensions is [[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]
The shape of the result is (1, 31, 1)


### f) Write code to do the following:

#### (i) Slice out the second row of var2 and print it.
#### (ii) Slice out the last column of var2 using the -1 notation and print it.
#### (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [25]:
# Changing var2 for the sake of this question
var2 = np.arange(0,30)
var2 = var2.reshape(5,6)
var2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
# Solving (i)
print(var2[1,:])

[ 6  7  8  9 10 11]


In [26]:
# Solving (ii)
print(var2[:,-1])

[ 5 11 17 23 29]


In [27]:
# Solving (iii)
print(var2[:2,-2:])

[[ 4  5]
 [10 11]]
