# DSTT Assignment 2

## Q1

### a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive. Print var1 and its shape. Hint : arange

In [1]:
#Importing numpy
import numpy as np

var1 = np.arange(0,31)

print(f"The shape of the array is {var1.shape}")
print(var1)

The shape of the array is (31,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


### b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2. Print var2 and its shape. Hint: Use the reshape function

In [2]:
var2 = var1.reshape(31,1)

print(f"The shape of var2 is {var2.shape}")
print(var2)

The shape of var2 is (31, 1)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]
 [26]
 [27]
 [28]
 [29]
 [30]]


### c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape. Print var3 and its shape.

In [3]:
var3 = var1.reshape(1,31,1)

print(f"The shape of var3 is {var3.shape}")
print(var3)

The shape of var3 is (1, 31, 1)
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


### d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1. Now look at var1 and var3. Did they change? Explain what’s going on. (Hint: does reshape return a view or a copy?)

In [4]:
var2[1,0] = -1

print(var1)

[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]


In [5]:
print(var3)

[[[ 0]
  [-1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]
  [13]
  [14]
  [15]
  [16]
  [17]
  [18]
  [19]
  [20]
  [21]
  [22]
  [23]
  [24]
  [25]
  [26]
  [27]
  [28]
  [29]
  [30]]]


### Answer:-

As we can see that changing a value in var2, reflected the same in var1 and var3, at the respective position where the element would have been if reshaped to their shapes. The reason behind it is that the reshape function returns a view of the original numpy array, and thus any change in the view gets reflected in the original numpy array

### e) Another thing that comes up a lot with array shapes is thinking about how to aggregate over specific dimensions. Figure out how the NumPy sum function works (and the axis argument in particular) and do the following:

#### (i) Sum var3 over its second dimension and print the result.

#### (ii) Sum var3 over its third dimension and print the result.

#### (iii) Sum var3 over both its first and third dimensions and print the result.

In [6]:
# Solving (i)

result_sec_dim = np.sum(var3, axis=1)
print(f"The sum over second dimension is {result_sec_dim}")
print(f"The shape of the result is {result_sec_dim.shape}")

The sum over second dimension is [[463]]
The shape of the result is (1, 1)


In [7]:
# Solving (ii)
result_third_dim = np.sum(var3, axis=2)
print(f"The sum over third dimension is {result_third_dim}")
print(f"The shape of the result is {result_third_dim.shape}")

The sum over third dimension is [[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30]]
The shape of the result is (1, 31)


In [8]:
#Solving (iii)
result_first_third_dim = np.sum(var3, axis=(0,2))
print(f"The sum over first and third dimensions is {result_first_third_dim}")
print(f"The shape of the result is {result_first_third_dim.shape}")

The sum over first and third dimensions is [ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
The shape of the result is (31,)


### f) Write code to do the following:

#### (i) Slice out the second row of var2 and print it.
#### (ii) Slice out the last column of var2 using the -1 notation and print it.
#### (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.

In [9]:
# Changing var2 for the sake of this question
var2 = np.arange(0,30)
var2 = var2.reshape(5,6)
var2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [10]:
# Solving (i)
print(var2[1,:])

[ 6  7  8  9 10 11]


In [11]:
# Solving (ii)
print(var2[:,-1])

[ 5 11 17 23 29]


In [12]:
# Solving (iii)
print(var2[:2,-2:])

[[ 4  5]
 [10 11]]


## Q2

### a) The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [13]:
vec = np.arange(10) + 1
print(vec)

[ 1  2  3  4  5  6  7  8  9 10]


### b) Now, create a $10 × 10$ matrix $A$ in which $A_{ij}$ = $i + j$. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.

In [14]:
vec_re = vec.reshape(10,1)
A = vec + vec_re
print(A)

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]


### c) A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples,each with five dimensions.

### d) You don’t worry too much about what this code is doing at this stage of the course, but for completeness: it imports the NumPy random number generation library, then generates a 50 × 5 matrix of standard normal random variates and exponentiates them. The effect of this is to have a pretend data set of 50 independent and identically-distributed vectors from a log-normal distribution.

In [15]:
import numpy.random as npr
data = np.exp(npr.randn(50, 5))
print(data.shape)
data

(50, 5)


array([[ 0.76726836,  0.14267619,  0.31653475,  1.52560434,  4.07994942],
       [ 3.24053387,  2.17771929,  1.22511116,  1.12786237,  0.36549042],
       [ 0.53703569,  0.58875977,  0.95937785,  0.35294559,  0.13192316],
       [ 0.41884325,  0.69952951,  0.95240402,  0.26314588,  2.04734551],
       [ 5.54113206,  0.08050558,  0.72832711,  3.42531903,  0.13944204],
       [ 1.70502603,  7.62687777,  1.90357853,  2.814918  ,  0.96730987],
       [ 0.73474338,  0.81456704,  2.37801248,  1.53880245,  1.59937522],
       [ 1.87618104,  2.61967095,  2.5817018 ,  0.3066591 ,  1.46570737],
       [ 9.74384876,  3.22486677,  1.10736831,  0.4920357 ,  0.79755044],
       [ 0.13894374,  6.77670117, 11.32422703,  4.10287036,  0.55530855],
       [ 0.24702907,  0.24355708,  0.54602647,  1.76825463,  2.27186317],
       [ 1.00010161,  0.30851727,  0.64225767,  0.17047813,  0.4757128 ],
       [ 3.29168982,  1.45595481,  1.58965922,  0.97578393,  0.58826478],
       [ 0.7362895 ,  1.8370549 ,  0.2

### e) Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [16]:
mean_dist = np.mean(data, axis=0)
std_dist = np.std(data, axis=0)
print(f"Mean of data along columns:- {mean_dist}")
print(f"Standard deviation of data along columns:- {std_dist}")

Mean of data along columns:- [1.94884149 1.61460124 1.96464923 1.75169474 1.64588397]
Standard deviation of data along columns:- [2.8290913  1.62770684 2.61796922 2.52682143 1.98487804]


### f) Now standardize the data matrix by:-
 1) subtracting the mean off of each column
 2) dividing each column by its standard deviation.

### Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [17]:
data_sub = data - mean_dist
normalized = data_sub / std_dist

normalized_mean_dist = np.mean(normalized, axis=0)
normalized_std_dist = np.std(normalized, axis=0)

print(f"Mean of normalized data along columns:- {normalized_mean_dist}")
print(f"Standard deviation of normalized data along columns:- {normalized_std_dist}")


Mean of normalized data along columns:- [ 2.33146835e-17 -4.44089210e-17 -1.57651669e-16  2.18713936e-16
 -8.88178420e-18]
Standard deviation of normalized data along columns:- [1. 1. 1. 1. 1.]


We can clearly verify that the mean of normalized data along columns is tending to 0 as the values are in the order of $10^{-16}$ or less.

## Q3

### a) A Vandermonde matrix is a matrix generated from a vector in which each column of the matrix is an integer power starting from zero. So, if I have a column vector $[x_{1}, x_{2}, . . . , x_{N}]^{T}$ , then the associated (square) Vandermonde matrix would be
$V = $
\[
\begin{bmatrix}
1 & x_1 & x_1^2 & \ldots & x_1^{N-1} \\
1 & x_2 & x_2^2 & \ldots & x_2^{N-1} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_N & x_N^2 & \ldots & x_N^{N-1}
\end{bmatrix}
\]

### Use what you learned about broadcasting in the previous problem to write a function that will produce a Vandermonde matrix for a vector $[1, 2, . . . ,N]^{T}$ for any N. Do it without using a loop.

### Use your function for N = 12, store it in variable named vander, and print the result.

In [18]:
def vandermonde(N):
    vec = np.arange(N) + 1
    vec_re = vec.reshape(N,1)

    vander_matrix = vec_re.astype(np.int64) ** np.arange(N)

    return vander_matrix

In [19]:
vander = vandermonde(12)
print(vander)

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

### b) Now, let’s make a pretend linear system problem with this matrix. Create a vector of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of vander with the vector you just created and store that in a new vector and call it b. Print the vector b.

In [20]:
x = np.ones(12,dtype=np.float64)
b = np.dot(vander,x)
print(b)

[1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 9.81706810e+09
 3.53036921e+10 1.11111111e+11 3.13842838e+11 8.10554586e+11]


### c) First, solve the linear system the naïve way, pretending like you don’t know x. Import numpy.linalg, invert V and multiply it by b. Print out your result. What should you get for your answer? If the answer is different than what you expected, write a sentence about that difference.

In [21]:
import numpy.linalg as nlg

V = vander
inv_V = nlg.inv(V)

result = np.dot(inv_V, b)

print(result)

[-72.11914062  71.140625     5.5703125   -0.58203125   0.97460938
   1.02441406   0.9979248    1.00009155   0.99999809   1.
   1.           1.        ]


The actual answer should have been $x = [1,1,1,1,1,1,1,1,1,1,1,1]$

Instead of that, we are getting some values which are no way closer to 1. The issue might have been while computing the inverse, as when we compute the pseudo inverse for this scenario, we are getting something close to $x$, which can be seen in the below block of code.

In [22]:
p_inv_V = nlg.pinv(V)

result_pinv = np.dot(p_inv_V, b)

print(result_pinv)

[0.99951172 1.00024414 1.00028229 0.99975586 1.         1.
 0.99996948 1.00000763 0.99999857 1.00000006 1.         1.        ]


We can clearly see these values are really close to $x$

### d) Now, solve the same linear system using solve. Print out the result. Does it seem more or less in line with what you’d expect?

In [23]:
result_using_solve = nlg.solve(V, b)
print(result_using_solve)

[1.07647578 0.77410766 1.27460353 0.81535555 1.07724566 0.97869803
 1.00397927 0.99949356 1.00004324 0.99999763 1.00000008 1.        ]


This seems more in line with what I expect as almost all values are quite closer to $x = [1,1,1,1,1,1,1,1,1,1,1,1]$