# QR Factorization using Gramm Schmidt

In [9]:
import numpy as np

def qr_gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for j in range(n):
        v = A[:, j]
        for i in range(j):
            R[i, j] = np.dot(Q[:, i].T, A[:, j])
            v -= R[i, j] * Q[:, i]
        R[j, j] = np.linalg.norm(v)
        Q[:, j] = v / R[j, j]

    return Q.round(3), R.round(3)

In [11]:
# Create a matrix A
A = np.array([[1., 2., 0.], [0., 1., 1.], [1., 0., 1.]])

# Perform QR factorization using the Gram-Schmidt process
Q, R = qr_gram_schmidt(A)

# Print the orthogonal matrix Q
print("Orthogonal matrix Q:")
print(Q)
print("*"*50)
# Print the upper triangular matrix R
print("Upper triangular matrix R:")
print(R)


Orthogonal matrix Q:
[[ 0.707  0.577 -0.408]
 [ 0.     0.577  0.816]
 [ 0.707 -0.577  0.408]]
**************************************************
Upper triangular matrix R:
[[1.414 1.414 0.707]
 [0.    1.732 0.   ]
 [0.    0.    1.225]]
