# Singular Value Decomposition

In [11]:
import numpy as np

def svd(matrix):
    # Compute U
    AAT = np.dot(matrix, matrix.T)
    eigenvalues_U, eigenvectors_U = np.linalg.eig(AAT)
    normalized_eigenvectors_U = eigenvectors_U / np.linalg.norm(eigenvectors_U, axis=0)
    U = normalized_eigenvectors_U

    # Compute V
    ATA = np.dot(matrix.T, matrix)
    eigenvalues_V, eigenvectors_V = np.linalg.eig(ATA)
    normalized_eigenvectors_V = eigenvectors_V / np.linalg.norm(eigenvectors_V, axis=0)
    V = normalized_eigenvectors_V

    # Compute S
    eigenvalues_S = np.sqrt(np.abs(eigenvalues_U))
    S = np.zeros_like(matrix)
    np.fill_diagonal(S, eigenvalues_S)

    return U.round(3), S.round(3), V.round(3)


In [12]:
# Example usage
A = np.array([[1., 0., 1., 0.], [0., 1., 0., 1.]])
U, S, V = svd(A)

print("U:")
print(U)
print("*"*50)
print("S:")
print(S)
print("*"*50)
print("V:")
print(V)


U:
[[1. 0.]
 [0. 1.]]
**************************************************
S:
[[1.414 0.    0.    0.   ]
 [0.    1.414 0.    0.   ]]
**************************************************
V:
[[ 0.707  0.707  0.     0.   ]
 [ 0.     0.    -0.707 -0.707]
 [ 0.707 -0.707  0.     0.   ]
 [ 0.     0.    -0.707  0.707]]
